### PR TITLE
Create a "Create Referral Program" UI Robot Test & Create a Github Action for Robot Tests

### PR DESCRIPTION
**Pull request by Julian88Tex**
# Critical Changes

# Changes
- created a "Create Referral Program" UI Robot test
  - to run test local use command `cci task run robot -o suites robot/01HousingandHomelessness/tests/browser/create_referral_program.robot --org <orgname>` 
- created Robot GitHub action
- consolidated GitHub jobs for all tests into one action

# Issues Closed

### CODE REVIEW

**Comment by Julian88Tex** [comment]
@szeitz Here's an example of a UI Robot Test running in Github. When we meet again, I'll demo this for you but in the meantime feel free to run it locally if you have an org and cci setup with the following terminal commands:

- `cci flow run qa_org --org qa`
- `cci task run robot -o suites robot/01HousingandHomelessness/tests/browser/create_referral_program.robot --org qa`

**Comment by Julian88Tex** [comment]
@mshanemc @jlantz this is ready for a review if either of y'all happens to be free. Thanks!

**Review by mshanemc — APPROVED** [review]
I have no opinion on robotFramework stuff.  None of this is in the package, so it's
1. probably harmless
2. easily changeable (packaged stuff is not!)

**Comment by Julian88Tex** [comment]
@mshanemc thanks for the review!

**Pull request merged**
